import { defaultBunSpawnRunner } from "../github/client";
import type { DiagnosticDetails, FailureContext } from "./types";

export function formatFailureDiagnosticComment(
	diagnostics: DiagnosticDetails,
): string {
	const output =
		diagnostics.validationOutput?.trim() || "No validation logs captured.";

	return `> *This was generated by Sandcastle autonomous runner during execution failure.*

## ❌ Execution Failure Diagnostic Report

- **Issue**: #${diagnostics.issueNumber} - ${diagnostics.title}
- **Branch**: \`${diagnostics.branch}\`
- **Failure Reason**: ${diagnostics.reason}
- **Attempts Taken**: ${diagnostics.attempts} / ${diagnostics.maxAttempts}
- **Duration**: ${diagnostics.durationMs}ms

### 🛠️ Resume Instructions
\`\`\`bash
git fetch origin && git checkout ${diagnostics.branch}
bun install
bun run validate
\`\`\`

<details>
<summary>🔍 Failure Logs & Output</summary>

\`\`\`
${output}
\`\`\`
</details>`;
}

export async function handleExecutionFailure(
	context: FailureContext,
): Promise<void> {
	const runner = context.gitRunner ?? defaultBunSpawnRunner;

	// 1. Push partial branch to origin (best-effort)
	try {
		await runner(["git", "push", "origin", context.branch], {
			cwd: context.worktreePath ?? context.cwd,
		});
	} catch {
		// Best-effort push; continue recovery on failure
	}

	// 2. Remove ready-for-agent, add ready-for-human
	try {
		await context.githubClient.updateLabels(context.issueNumber, {
			add: ["ready-for-human"],
			remove: ["ready-for-agent"],
		});
	} catch {
		// Best-effort label update
	}

	// 3. Remove runner assignee (@me)
	try {
		await context.githubClient.releaseClaim(context.issueNumber);
	} catch {
		// Best-effort claim release
	}

	// 4. Post structured diagnostic comment
	try {
		const comment = formatFailureDiagnosticComment({
			attempts: context.attempts,
			branch: context.branch,
			durationMs: context.durationMs,
			issueNumber: context.issueNumber,
			maxAttempts: context.maxAttempts,
			reason: context.reason,
			title: context.issueTitle,
			validationOutput: context.validationOutput,
		});
		await context.githubClient.addComment(context.issueNumber, comment);
	} catch {
		// Best-effort diagnostic comment
	}
}
