/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrototypeAuthRouteImport } from './routes/prototype/auth'
import { Route as VodsIndexRouteImport } from './routes/vods/index'
import { Route as VodsIdRouteImport } from './routes/vods/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as VodsIdSessionRouteImport } from './routes/vods/$id.session'
import { Route as ApiVodsIdManifestRouteImport } from './routes/api/vods/$id/manifest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeAuthRoute = PrototypeAuthRouteImport.update({
  id: '/prototype/auth',
  path: '/prototype/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VodsIndexRoute = VodsIndexRouteImport.update({
  id: '/vods/',
  path: '/vods/',
  getParentRoute: () => rootRouteImport,
} as any)
const VodsIdRoute = VodsIdRouteImport.update({
  id: '/vods/$id',
  path: '/vods/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VodsIdSessionRoute = VodsIdSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => VodsIdRoute,
} as any)
const ApiVodsIdManifestRoute = ApiVodsIdManifestRouteImport.update({
  id: '/api/vods/$id/manifest',
  path: '/api/vods/$id/manifest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prototype/auth': typeof PrototypeAuthRoute
  '/vods/$id': typeof VodsIdRouteWithChildren
  '/vods/': typeof VodsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/vods/$id/session': typeof VodsIdSessionRoute
  '/api/vods/$id/manifest': typeof ApiVodsIdManifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prototype/auth': typeof PrototypeAuthRoute
  '/vods/$id': typeof VodsIdRouteWithChildren
  '/vods': typeof VodsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/vods/$id/session': typeof VodsIdSessionRoute
  '/api/vods/$id/manifest': typeof ApiVodsIdManifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prototype/auth': typeof PrototypeAuthRoute
  '/vods/$id': typeof VodsIdRouteWithChildren
  '/vods/': typeof VodsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/vods/$id/session': typeof VodsIdSessionRoute
  '/api/vods/$id/manifest': typeof ApiVodsIdManifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prototype/auth'
    | '/vods/$id'
    | '/vods/'
    | '/api/auth/$'
    | '/api/media/$'
    | '/vods/$id/session'
    | '/api/vods/$id/manifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prototype/auth'
    | '/vods/$id'
    | '/vods'
    | '/api/auth/$'
    | '/api/media/$'
    | '/vods/$id/session'
    | '/api/vods/$id/manifest'
  id:
    | '__root__'
    | '/'
    | '/prototype/auth'
    | '/vods/$id'
    | '/vods/'
    | '/api/auth/$'
    | '/api/media/$'
    | '/vods/$id/session'
    | '/api/vods/$id/manifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrototypeAuthRoute: typeof PrototypeAuthRoute
  VodsIdRoute: typeof VodsIdRouteWithChildren
  VodsIndexRoute: typeof VodsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  ApiVodsIdManifestRoute: typeof ApiVodsIdManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/auth': {
      id: '/prototype/auth'
      path: '/prototype/auth'
      fullPath: '/prototype/auth'
      preLoaderRoute: typeof PrototypeAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vods/': {
      id: '/vods/'
      path: '/vods'
      fullPath: '/vods/'
      preLoaderRoute: typeof VodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vods/$id': {
      id: '/vods/$id'
      path: '/vods/$id'
      fullPath: '/vods/$id'
      preLoaderRoute: typeof VodsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vods/$id/session': {
      id: '/vods/$id/session'
      path: '/session'
      fullPath: '/vods/$id/session'
      preLoaderRoute: typeof VodsIdSessionRouteImport
      parentRoute: typeof VodsIdRoute
    }
    '/api/vods/$id/manifest': {
      id: '/api/vods/$id/manifest'
      path: '/api/vods/$id/manifest'
      fullPath: '/api/vods/$id/manifest'
      preLoaderRoute: typeof ApiVodsIdManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VodsIdRouteChildren {
  VodsIdSessionRoute: typeof VodsIdSessionRoute
}

const VodsIdRouteChildren: VodsIdRouteChildren = {
  VodsIdSessionRoute: VodsIdSessionRoute,
}

const VodsIdRouteWithChildren =
  VodsIdRoute._addFileChildren(VodsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrototypeAuthRoute: PrototypeAuthRoute,
  VodsIdRoute: VodsIdRouteWithChildren,
  VodsIndexRoute: VodsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  ApiVodsIdManifestRoute: ApiVodsIdManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
