import { describe, expect, it } from "vitest";
import { MockGithubClient } from "../../github/client";
import type { ProcessRunner } from "../../github/types";
import {
	formatFailureDiagnosticComment,
	handleExecutionFailure,
} from "../failure-handler";
import type { DiagnosticDetails, FailureContext } from "../types";

describe("Failure Diagnostics and Recovery", () => {
	describe("formatFailureDiagnosticComment", () => {
		it("formats full diagnostic comment with validation output and AI disclaimer", () => {
			// Arrange
			const details: DiagnosticDetails = {
				attempts: 3,
				branch: "feat/issue-165-lifecycle",
				durationMs: 4500,
				issueNumber: 165,
				maxAttempts: 3,
				reason: "Validation checks failed at step 'check:types'",
				title: "Execution Lifecycle",
				validationOutput:
					"src/main.ts(10,5): error TS2322: Type 'string' is not assignable to type 'number'.",
			};

			// Act
			const comment = formatFailureDiagnosticComment(details);

			// Assert
			expect(comment).toContain(
				"> *This was generated by Sandcastle autonomous runner during execution failure.*",
			);
			expect(comment).toContain("## ❌ Execution Failure Diagnostic Report");
			expect(comment).toContain("- **Issue**: #165 - Execution Lifecycle");
			expect(comment).toContain("- **Branch**: `feat/issue-165-lifecycle`");
			expect(comment).toContain(
				"- **Failure Reason**: Validation checks failed at step 'check:types'",
			);
			expect(comment).toContain("- **Attempts Taken**: 3 / 3");
			expect(comment).toContain("- **Duration**: 4500ms");
			expect(comment).toContain("### 🛠️ Resume Instructions");
			expect(comment).toContain(
				"git fetch origin && git checkout feat/issue-165-lifecycle\nbun install\nbun run validate",
			);
			expect(comment).toContain("<details>");
			expect(comment).toContain("<summary>🔍 Failure Logs & Output</summary>");
			expect(comment).toContain(
				"src/main.ts(10,5): error TS2322: Type 'string' is not assignable to type 'number'.",
			);
		});

		it("formats diagnostic comment with fallback message when validation output is empty", () => {
			// Arrange
			const details: DiagnosticDetails = {
				attempts: 1,
				branch: "feat/issue-100-crash",
				durationMs: 1200,
				issueNumber: 100,
				maxAttempts: 3,
				reason: "Unexpected sandbox crash",
				title: "Crash Issue",
			};

			// Act
			const comment = formatFailureDiagnosticComment(details);

			// Assert
			expect(comment).toContain("No validation logs captured.");
			expect(comment).toContain("- **Issue**: #100 - Crash Issue");
		});
	});

	describe("handleExecutionFailure", () => {
		it("pushes partial branch, transitions labels, releases assignee, and posts diagnostic comment", async () => {
			// Arrange
			const githubClient = new MockGithubClient([
				{
					assignees: ["@me"],
					body: "Issue body",
					issueDependenciesSummary: { blockedBy: 0 },
					labels: ["ready-for-agent", "enhancement"],
					number: 165,
					title: "Execution Lifecycle",
				},
			]);

			let pushedBranch = "";
			const gitRunner: ProcessRunner = async (cmd) => {
				if (cmd[0] === "git" && cmd[1] === "push") {
					pushedBranch = cmd[3];
				}
				return { exitCode: 0, stderr: "", stdout: "" };
			};

			const context: FailureContext = {
				attempts: 3,
				branch: "feat/issue-165-lifecycle",
				durationMs: 3200,
				githubClient,
				gitRunner,
				issueNumber: 165,
				issueTitle: "Execution Lifecycle",
				maxAttempts: 3,
				reason: "Verification tests failed",
				validationOutput: "1 test failed: expected 2 to be 3",
				worktreePath: "/tmp/worktree/feat-165",
			};

			// Act
			await handleExecutionFailure(context);
			const updatedIssue = await githubClient.getIssue(165);
			const comments = githubClient.getComments(165);

			// Assert
			expect(pushedBranch).toBe("feat/issue-165-lifecycle");
			expect(updatedIssue.labels).toEqual(["enhancement", "ready-for-human"]);
			expect(updatedIssue.assignees).toEqual([]);
			expect(comments).toHaveLength(1);
			expect(comments[0]).toContain("❌ Execution Failure Diagnostic Report");
			expect(comments[0]).toContain("1 test failed: expected 2 to be 3");
		});

		it("resiliently continues teardown and posts comment even if git push throws or fails", async () => {
			// Arrange
			const githubClient = new MockGithubClient([
				{
					assignees: ["@me"],
					body: "Issue body",
					issueDependenciesSummary: { blockedBy: 0 },
					labels: ["ready-for-agent"],
					number: 170,
					title: "Network fail issue",
				},
			]);

			const failingGitRunner: ProcessRunner = async () => {
				throw new Error("Network connection lost during git push");
			};

			const context: FailureContext = {
				attempts: 2,
				branch: "feat/issue-170",
				durationMs: 1500,
				githubClient,
				gitRunner: failingGitRunner,
				issueNumber: 170,
				issueTitle: "Network fail issue",
				maxAttempts: 3,
				reason: "Failed due to network",
			};

			// Act
			await handleExecutionFailure(context);
			const updatedIssue = await githubClient.getIssue(170);
			const comments = githubClient.getComments(170);

			// Assert
			expect(updatedIssue.labels).toEqual(["ready-for-human"]);
			expect(updatedIssue.assignees).toEqual([]);
			expect(comments).toHaveLength(1);
		});

		it("resiliently continues when label update or comment posting encounters error", async () => {
			// Arrange
			const githubClient = new MockGithubClient([
				{
					assignees: ["@me"],
					body: "Issue body",
					issueDependenciesSummary: { blockedBy: 0 },
					labels: ["ready-for-agent"],
					number: 180,
					title: "Comment failure issue",
				},
			]);
			githubClient.simulateAddCommentFailure("GitHub API 500 error");

			const context: FailureContext = {
				attempts: 1,
				branch: "feat/issue-180",
				durationMs: 900,
				githubClient,
				issueNumber: 180,
				issueTitle: "Comment failure issue",
				maxAttempts: 3,
				reason: "Some failure",
			};

			// Act
			await handleExecutionFailure(context);
			const updatedIssue = await githubClient.getIssue(180);

			// Assert
			expect(updatedIssue.labels).toEqual(["ready-for-human"]);
			expect(updatedIssue.assignees).toEqual([]);
		});

		it("uses default process runner when gitRunner is not supplied", async () => {
			// Arrange
			const githubClient = new MockGithubClient([
				{
					assignees: ["@me"],
					body: "Issue body",
					issueDependenciesSummary: { blockedBy: 0 },
					labels: ["ready-for-agent"],
					number: 190,
					title: "Default runner issue",
				},
			]);

			const context: FailureContext = {
				attempts: 1,
				branch: "feat/issue-190",
				durationMs: 800,
				githubClient,
				issueNumber: 190,
				issueTitle: "Default runner issue",
				maxAttempts: 3,
				reason: "Check failed",
			};

			// Act
			await handleExecutionFailure(context);
			const updatedIssue = await githubClient.getIssue(190);

			// Assert
			expect(updatedIssue.labels).toEqual(["ready-for-human"]);
		});
	});
});
