name: "Setup Browsers"
description: "Caches and installs browser binaries and operating system dependencies"

inputs:
  browsers:
    default: "chromium"
    description: "Space-separated list of browsers to install (e.g. 'chromium' or 'chromium firefox')"
    required: false

runs:
  using: "composite"
  steps:
    - name: 💾 Cache Browser Binaries
      id: browser-cache
      uses: actions/cache@v5
      with:
        key: ${{ runner.os }}-browser-${{ inputs.browsers }}-${{ hashFiles('**/bun.lock') }}
        path: ~/.cache/ms-playwright
        restore-keys: |
          ${{ runner.os }}-browser-${{ inputs.browsers }}-
          ${{ runner.os }}-browser-

    - name: 🧩 Install Browser System Dependencies
      if: runner.os == 'Linux'
      run: bunx playwright install-deps ${{ inputs.browsers }}
      shell: bash

    - name: 🌐 Install Browser Binaries
      if: steps.browser-cache.outputs.cache-hit != 'true'
      run: bunx playwright install ${{ inputs.browsers }}
      shell: bash
