/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.config/wrangler.json --include-runtime=false src/cloudflare-env.d.ts` (hash: 2912b2314d4089013a4ad3352c5d210c)
interface __BaseEnv_Env {
	DB: D1Database;
	BETTER_AUTH_URL: "https://watchpoint.jackmaders.workers.dev";
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET">> {}
}
