/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.config/wrangler.json --include-runtime=false src/cloudflare-env.d.ts` (hash: fd647a2623f8b553e3c9d6e389b8e6dd)
interface __BaseEnv_Env {
	DB: D1Database;
	BETTER_AUTH_URL: "https://watchpoint.jackmaders.workers.dev";
	SENTRY_DSN: "https://ad62fa82e1f47662f8ed69f2d6ef84f5@o4511871149670400.ingest.de.sentry.io/4511871151243344";
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "SENTRY_DSN" | "BETTER_AUTH_SECRET">> {}
}
