/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.config/wrangler.json --include-runtime=false src/cloudflare-env.d.ts` (hash: ba34b99e286c6707b934117d57d39b50)
interface __BaseEnv_Env {
	DB: D1Database;
	BETTER_AUTH_URL: "https://watchpoint.jackmaders.workers.dev";
	POSTHOG_HOST: "https://us.i.posthog.com";
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "POSTHOG_HOST" | "BETTER_AUTH_SECRET">> {}
}
